enforce_secure_profile: false
listeners:
- query_port: 31544
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: false
  host: 127.0.0.1:25577
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: df1c785f-c6a4-43bc-994c-c63b03c26265
player_limit: -1
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: "\tยง6BURGERCRAFTX: WHY ARE YOU PLAYING ON EAGLER? PLAY ON SKLAUNCHER BOZO"
    address: scuffedmc.falixsrv.me:31544
    restricted: false
